name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Login DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker frontend image
        run: cd frontend && docker build -t youssefelmajdoul/rentcaremirats-frontend:latest .

      - name: Push the frontend to DockerHub
        run: docker push youssefelmajdoul/rentcaremirats-frontend:latest

      - name: Build the Docker backend image
        run: cd backend && mvn clean package && docker build -t youssefelmajdoul/rentcaremirats-backend:latest .

      - name: Push the backend to DockerHub
        run: docker push youssefelmajdoul/rentcaremirats-backend:latest
